apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-of-apps
  namespace: argocd
  # This will Delete all the k8 resources created by this app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Delete=true

  destination:
    name: in-cluster
    namespace: argocd

  sources:
    - repoURL: ' https://github.com/cdsre/argocd-playground.git'
      targetRevision: 'main'
      path: 'apps/consul'
    - repoURL: ' https://github.com/cdsre/argocd-playground.git'
      targetRevision: 'main'
      path: 'apps/prometheus'