apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  # This will Delete all the k8 resources created by this app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Delete=true

  destination:
    name: in-cluster
    namespace: vault

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.1

    helm:
      valuesObject:
        global:
          enabled: true
          namespace: vault
          tlsDisable: true
        injector:
          enabled: false
        ui:
          enabled: true
          serviceType: "LoadBalancer"
